[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Camas"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "solve"
path = "solve.rs"

[dependencies]
clap = "2.33"
clipboard = "0.5"
num-derive = "0.3"
num-traits = "0.2"
num-integer = "0.1"
itertools = "0.8"
impl_ops = "0.1"
